package org.zerionproject.core.api.crypto;

public interface PostQuantumConstants {

	int ML_KEM_768_PUBLIC_KEY_BYTES = 1184;

	int ML_KEM_768_PRIVATE_KEY_BYTES = 2400;

	int ML_KEM_768_CIPHERTEXT_BYTES = 1088;

	int ML_KEM_768_SHARED_SECRET_BYTES = 32;

	int ML_DSA_65_PUBLIC_KEY_BYTES = 1952;

	int ML_DSA_65_PRIVATE_KEY_BYTES = 4032;

	int ML_DSA_65_SIGNATURE_BYTES = 3309;

	int HYBRID_AGREEMENT_PUBLIC_KEY_BYTES = 32 + ML_KEM_768_PUBLIC_KEY_BYTES;

	int HYBRID_AGREEMENT_PRIVATE_KEY_BYTES = 32 + ML_KEM_768_PRIVATE_KEY_BYTES;

	int HYBRID_SIGNATURE_PUBLIC_KEY_BYTES = 32 + ML_DSA_65_PUBLIC_KEY_BYTES;

	int HYBRID_SIGNATURE_PRIVATE_KEY_BYTES = 32 + ML_DSA_65_PRIVATE_KEY_BYTES;

	int HYBRID_SIGNATURE_BYTES = 64 + ML_DSA_65_SIGNATURE_BYTES;

	byte KEY_AGREEMENT_PROTOCOL_VERSION_HYBRID = 5;

	byte CONTACT_EXCHANGE_PROTOCOL_VERSION_HYBRID = 2;

	int HANDSHAKE_LINK_FORMAT_VERSION_HYBRID = 1;

	String KEY_TYPE_HYBRID_AGREEMENT = "Hybrid-X25519-ML-KEM-768";

	String KEY_TYPE_HYBRID_SIGNATURE = "Hybrid-Ed25519-ML-DSA-65";

	String HYBRID_SHARED_SECRET_LABEL =
			"org.zerionproject.core.crypto/HYBRID_SHARED_SECRET";

	String HYBRID_COMMITMENT_LABEL =
			"org.zerionproject.core.crypto/HYBRID_COMMITMENT";
}
