apply plugin: 'java-library'
sourceCompatibility = 17
targetCompatibility = 17

apply plugin: 'ru.vyarus.animalsniffer'

dependencies {
	implementation project(':zerion-core-api')

	signature 'org.codehaus.mojo.signature:java16:1.1@signature'

	testImplementation project(path: ':zerion-core-api', configuration: 'testOutput')

	testImplementation "junit:junit:$junit_version"
}
