package org.zerionproject.app.messaging;

public interface MessageTypes {

	int PRIVATE_MESSAGE = 0;
	int ATTACHMENT = 1;
	int VOICE_SIGNAL = 2;
	int ATTACHMENT_MANIFEST = 3;
	int ATTACHMENT_CHUNK = 4;
	int MESSAGE_REACTION = 7;
	int TYPING_INDICATOR = 8;
	int LINK_PREVIEW_MESSAGE = 9;
	int MESH_PREKEY_BUNDLE = 10;

	int GROUP_POST = 32;
	int GROUP_MEMBER_ADDED = 33;
	int GROUP_MEMBER_REMOVED = 34;
	int GROUP_MEMBER_LEFT = 35;
	int GROUP_DISSOLVED = 36;
	int GROUP_EPOCH_COMMIT = 37;
	int GROUP_MEMBER_ROLE_CHANGED = 38;
	int GROUP_MEMBER_KEY_ROTATED_RESERVED = 39;
	int GROUP_FORWARDED_RESERVED = 40;
	int GROUP_MEMBER_LIST_SNAPSHOT = 41;
	int GROUPTR_INVITE_OFFER = 42;
	int GROUPTR_INVITE_ACCEPT = 43;
	int GROUPTR_INVITE_DECLINE = 44;
}
